### ISSUE TITLE
[uni-form-item] Cannot specify width of text input in %

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#176]
I cannot specify width of text input as `100%` of the parent container. What am I doing wrong?

https://glitch.com/edit/#!/jumbled-yam?path=index.html:1:0

**Comment by tomalec** [comment]
We need to fix that in `uni-form-item` definition by changing:
```css
uni-form-item{
  grid-template: "label" / 1fr;
}
```
For now, you can apply this rule from the outside to workaround the problem https://glitch.com/edit/#!/magical-aardwolf?path=index.html:15:34
