### ISSUE TITLE
Style <aside> or implement a special class for side information

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#182]
As discussed in https://github.com/Starcounter/UniformDocs/pull/354#discussion_r209885004

**Comment by tomalec** [comment]
Initially I used slightly (`0.9`) dimmed `blockquote`  styles: 
![image](https://user-images.githubusercontent.com/17435/44260228-0d3dce00-a214-11e8-889f-6ebf6a565f12.png)

```css
aside {
   padding-left: var(--uni-section-padding-horizontal, var(--uni-default-section-padding-horizontal));
   border-left: 0.3rem solid var(--uni-blockquote-border-color, var(--uni-default-blockquote-border-color));
   opacity: 0.9;
}
```
