### ISSUE TITLE
Forms layout is missing

### ISSUE THREAD

**Issue by tomalec** [Starcounter/uniform.css#25]
All we have is 
```css
 .uni-form > ::slotted(div) {
   margin-bottom: 20px;
 }
 .uni-form > div {
   margin-bottom: 20px;
 }

 .uni-form > ::slotted(div:last-child) {
   margin-bottom: 10px;
 }
 .uni-form > div:last-child {
   margin-bottom: 10px;
 }
```

What rarely serves any purpose, especially given, the views should give mosly `<input>`s and `<label>`s not `<div>`s.
