### ISSUE TITLE
Revisit `.uni-class::slotted(*)` selectors

### ISSUE THREAD

**Issue by tomalec** [Starcounter/uniform.css#9]
Recently we decided to use `.uni-class::slotted(*)` over `.uni-class>::slotted(*)` and `.uni-class ::slotted(*)` in some cases.

I still think it's nicer, cleaner and more semantic. But... polyfill.

In polyfilled Shadow DOM, there is no `<slot>` element in the actual DOM, therefore, there is no element on which class https://jsbin.com/yayoyaw/edit?html,output
https://github.com/webcomponents/shadycss/issues/155

I suggest to get back to `.uni-class>::slotted(*)`

//cc @warpech  @PatrykSzwer

**Comment by warpech** [comment]
Ok, this means there is really no argument about it.

@PatrykSzwer please work on that on Monday.

@tomalec I suppose this is the reason why my snippet in https://github.com/Starcounter/starcounter-include/issues/85 does not work? If yes, then please feel free to close that issue.

**Comment by tomalec** [comment]
Actually your snippet should work. You can make it:
```css
 .wrap-my-button>::slotted(button) { 
     background: green; 
 }
 .wrap-my-button>button { 
     background: green; 
 } 
```
http://jsbin.com/saxafo/3/edit?html,output


My examples were non-polyfillable.
